language: swift
xcode_project: safe.xcodeproj
xcode_scheme: safe
osx_image: xcode9.2
before_install:
  - brew update
  - brew upgrade swiftlint swiftgen
script:
  - bundle exec fastlane test || cat /Users/travis/Library/Logs/scan/safe-safe.log
