language: swift
osx_image: xcode9.4
cache:
  - bundler
  - pip
  directories:
    - $HOME/.rvm/
branches:
  only:
  - master
  - "/release\\/.*/"
env:
  global:
  # include $HOME/.local/bin for `aws`
  - PATH=$HOME/.local/bin:$PATH

matrix:
  include:
    - name: "Common Tests"
      env: 
        - TEST_SUITE=only:CommonTests,DatabaseTess,CommonImplementationTests
        - TEST_SUITE_NAME=Common
    - name: "IdentityAccess Tests"
      env: 
        - TEST_SUITE=only:IdentityAccessDomainModelTests,IdentityAccessApplicationTests,IdentityAccessImplementationsTests
        - TEST_SUITE_NAME=IdentityAccess
    - name: "MultisigWallet Tests"
      env: 
        - TEST_SUITE=only:MultisigWalletDomainModelTests,MultisigWalletApplicationTests,MultisigWalletImplementationsTests
        - TEST_SUITE_NAME=MultisigWallet
    - name: "UI Unit Tests"
      env: 
        - TEST_SUITE=only:SafeUIKitTests,SafeAppUIUnitTests,safeTests
        - TEST_SUITE_NAME=SafeUI
    - name: "Smoke UI Tests"
      env: 
        - TEST_SUITE=only:SafeUITests/SmokeUITests
        - TEST_SUITE_NAME=Smoke
    - name: "UI Tests"
      env: 
        - "TEST_SUITE=only:SafeUITests,SafeUIKitDemoUITests skip:SafeUITests/SmokeUITests"
        - TEST_SUITE_NAME=UI

before_install:
  - sh scripts/decrypt_files.sh 
  # set up awscli packages
  - pip install --user awscli
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER
  - aws s3 sync s3://safe.gnosis.travis/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER


jobs:
  include:
    - stage: build
      #script: "bundle exec fastlane build_for_testing"
      # specifying env to have only one job from matrix for build stage
      env: TEST_SUITE=only:SafeUITests/SmokeUITests
      script: echo build | tee > ~/$TRAVIS_BUILD_NUMBER/build
    - stage: test
      before_install: cat ~/$TRAVIS_BUILD_NUMBER/build
      script: echo $TEST_SUITE | tee > ~/$TRAVIS_BUILD_NUMBER/$TEST_SUITE_NAME
    - stage: deploy
      script: cat ~/$TRAVIS_BUILD_NUMBER/*
      after_success:
        - aws s3 rm --recursive s3://safe.gnosis.travis/$TRAVIS_BUILD_NUMBER # clean up after ourselves
 
after_success:
#- scripts/travis_code_coverage.sh
  - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://safe.gnosis.travis/$TRAVIS_BUILD_NUMBER